gcp_credentials_file = "service-account.json"
region               = "us-central1"
zone                 = "us-central1-a"
ssh_public_key       = "~/.ssh/id_rsa.pub"
vm_name              = "devops-instance"
project_id           = "your-gcp-project-id"
