---
- hosts: servers
  become: yes
  vars_files:
    - users.yml
  vars:
    notebook_dir: /opt/pyspark-notebooks

  handlers:
    - name: Restart SSH safely
      block:
        - name: Validate sshd_config
          command: sshd -t
          register: sshd_check
          failed_when: sshd_check.rc != 0

        - name: Restart SSH
          service:
            name: ssh
            state: restarted
      rescue:
        - name: Restore sshd_config backup
          copy:
            src: /etc/ssh/sshd_config.bak
            dest: /etc/ssh/sshd_config
            remote_src: yes
        - name: Restart SSH after restore
          service:
            name: ssh
            state: restarted

  tasks:
    - name: Backup sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes

    - name: Ensure Port 22 exists
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Port 22'
        line: "Port 22"
        state: present
      notify: Restart SSH safely

    - name: Add user-specific SSH ports
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "Port {{ item.port }}"
        state: present
      loop: "{{ users }}"
      notify: Restart SSH safely
