---
- hosts: servers
  become: yes
  vars_files:
    - users.yml

  tasks:
    - name: Create users with hashed passwords
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Ensure UFW firewall is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow default SSH port 22 in UFW
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Add new SSH ports for each user to sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: '^#Port 22'
        line: "Port {{ item.port }}"
        state: present
      loop: "{{ users }}"
      notify: Restart SSH

    - name: Allow new SSH ports in UFW
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
      loop: "{{ users }}"

    - name: Enable UFW firewall
      community.general.ufw:
        state: enabled

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
